server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=CST&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    # 默认根据url进行识别
    driver-class-name: com.mysql.cj.jdbc.Driver
